### ISSUE TITLE
为什么jar添加到jmeter的lib\ext还是看不到dubbo sample

### ISSUE THREAD

**Issue by ericWenjp** [dubbo/jmeter-plugins-dubbo#29]
jmeter 版本 3.0；
jmeter-plugins-dubbo的版本1.3.6；
![image](https://user-images.githubusercontent.com/25905832/47199941-87bad380-d3a6-11e8-8df2-8fd60f2f9d9e.png)

**Comment by ningyu1** [comment]
@ericWenjp  你下的插件jar文件是不是损坏了？看看能否作为压缩包打开或者解压，还有一个就是尽量避免使用中文目录，jmeter对中文的支持并不好

**Comment by zonghai** [comment]
自己下载代码自己大包应该就可以了宗海------------------ 原始邮件 ------------------发件人: 凝雨  <notifications@github.com>发送时间: 2018年10月19日 15:56收件人: dubbo/jmeter-plugins-dubbo <jmeter-plugins-dubbo@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[dubbo/jmeter-plugins-dubbo] 为什么jar添加到jmeter的lib\ext还是看不到dubbo sample (#29)@ericWenjp  你下的插件jar文件是不是损坏了？看看能否作为压缩包打开或者解压，还有一个就是尽量避免使用中文目录，jmeter对中文的支持并不好

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dubbo/jmeter-plugins-dubbo","title":"dubbo/jmeter-plugins-dubbo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/dubbo/jmeter-plugins-dubbo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ningyu1 in #29: @ericWenjp  你下的插件jar文件是不是损坏了？看看能否作为压缩包打开或者解压，还有一个就是尽量避免使用中文目录，jmeter对中文的支持并不好"}],"action":{"name":"View Issue","url":"https://github.com/dubbo/jmeter-plugins-dubbo/issues/29#issuecomment-431277868"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dubbo/jmeter-plugins-dubbo/issues/29#issuecomment-431277868",
"url": "https://github.com/dubbo/jmeter-plugins-dubbo/issues/29#issuecomment-431277868",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [dubbo/jmeter-plugins-dubbo] 为什么jar添加到jmeter的lib\\ext还是看不到dubbo sample (#29)",
"sections": [
{
"text": "",
"activityTitle": "**凝雨**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ningyu1",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"dubbo/jmeter-plugins-dubbo\",\n\"issueId\": 29,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"dubbo/jmeter-plugins-dubbo\",\n\"issueId\": 29\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/dubbo/jmeter-plugins-dubbo/issues/29#issuecomment-431277868"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 398384008\n}"
}
],
"themeColor": "26292E"
}
]
